"""Seed Modelli Pipeline per sport outdoor: Triathlon, Nuoto in acque libere, Ciclismo su strada, Mountain Bike, Trail Running.
Usato solo per il primo popolamento idempotente (per key); poi i modelli vivono nel DB e sono gestiti dal Super Admin.
Le scadenze sono suggerimenti modificabili, non termini legali."""

V = "Verificare i requisiti effettivamente applicabili (normativa, ordinanze e regolamenti federali vigenti)."
PR = {"n": "normale", "i": "importante", "c": "critica"}


def T(titolo, categoria, off, pr="n", note="", crm=None):
    return {"titolo": titolo, "categoria": categoria, "giorni_offset": off, "priorita": PR[pr], "descrizione": note, "crm_section": crm}


def common(fed: str, disc: str) -> list:
    return [
        T("Definizione data, location e format dell'evento", "Logistica", -300, "c", f"Formato, distanze e capienza massima della gara di {disc}."),
        T("Verifica eventi concomitanti sul territorio e nel calendario federale", "Logistica", -280),
        T("Piano economico e budget preliminare", "Logistica", -270, "c", "Voci: enti, sicurezza, sanitario, cronometraggio, allestimenti, premi, comunicazione."),
        T(f"Richiesta inserimento a calendario {fed}", "Autorizzazioni", -240, "c", V),
        T("Regolamento gara e requisiti di partecipazione", "Iscrizioni", -180, "c", f"Tesseramento, certificato medico agonistico, limiti di età. {V}"),
        T("Richiesta autorizzazione ai Comuni interessati", "Autorizzazioni", -150, "c", V),
        T("Comunicazione a Prefettura e Questura", "Autorizzazioni", -120, "c", V),
        T("Polizza assicurativa RC organizzatore", "Autorizzazioni", -120, "c", V),
        T("Ricerca sponsor principali", "Sponsor e partner", -210, "i", crm="sponsors"),
        T("Definizione pacchetti di sponsorizzazione", "Sponsor e partner", -200, "n", crm="sponsors"),
        T("Contratti sponsor e raccolta loghi", "Sponsor e partner", -90, "i", crm="sponsors"),
        T("Scelta servizio di cronometraggio", "Logistica", -150, "c", "Fornitore: cronometraggio. Chip, tappeti, classifiche live.", "companies"),
        T("Definizione quote e scaglioni di iscrizione", "Iscrizioni", -160, "i"),
        T("Apertura iscrizioni online", "Iscrizioni", -150, "c"),
        T("Pagina evento con informazioni e regolamento", "Comunicazione", -160, "i"),
        T("Piano editoriale social e newsletter", "Comunicazione", -150),
        T("Comunicato stampa di lancio", "Comunicazione", -140),
        T("Definizione team operativi e fabbisogno volontari", "Staff e volontari", -120, "i", crm="staff"),
        T("Nomina Team Leader per ogni area", "Staff e volontari", -100, "i", crm="staff"),
        T("Campagna di reclutamento volontari", "Staff e volontari", -90, "i", crm="volunteers"),
        T("Organizzazione turni staff e volontari", "Staff e volontari", -30, "i", crm="staff"),
        T("Divise e pettorine staff", "Materiali", -60),
        T("Ordine pettorali", "Materiali", -45, "i", "Fornitore: tipografia o cronometraggio."),
        T("Definizione pacco gara e ordini", "Merchandising", -75),
        T("Medaglie, trofei e premi di categoria", "Merchandising", -75, "i"),
        T("Convenzione soccorso sanitario e ambulanze", "Sicurezza", -90, "c", f"Fornitore: servizio sanitario. {V}"),
        T("Piano sanitario e di emergenza", "Sicurezza", -60, "c", V),
        T("Piano comunicazioni radio di gara", "Sicurezza", -45, "i", "Canali, nominativi e procedure di chiamata."),
        T("Servizi igienici per atleti e pubblico", "Logistica", -30),
        T("Noleggio transenne, gazebo e materiali area partenza/arrivo", "Allestimenti", -30),
        T("Chiusura iscrizioni ed elenco partenti", "Iscrizioni", -7, "i"),
        T("Mail informativa finale agli atleti", "Comunicazione", -5, "i", "Orari, logistica, parcheggi, regolamento e materiale."),
        T("Briefing operativo staff e Team Leader", "Staff e volontari", -3, "i", crm="briefing"),
        T("Allestimento segreteria e area accrediti", "Allestimenti", -1),
        T("Consegna pettorali e pacchi gara", "Iscrizioni", -1, "i"),
        T("Premiazioni", "Allestimenti", 0, "i"),
        T("Gestione rifiuti e pulizia delle aree", "Logistica", 0, "i"),
        T("Smontaggio aree di gara", "Allestimenti", 0, "i"),
        T("Pubblicazione classifiche ufficiali", "Comunicazione", 1, "i"),
        T("Ringraziamenti a volontari e partner", "Post evento", 3, crm="volunteers"),
        T("Gallery foto/video e comunicato finale", "Comunicazione", 3),
        T("Riunione di analisi criticità", "Post evento", 14),
        T("Rendiconto economico e pagamento fornitori", "Post evento", 30, "i"),
        T("Chiusura amministrativa e documentazione agli enti", "Post evento", 30, "i"),
        T("Report finale dell'evento", "Post evento", 30),
    ]


TRIATHLON = [
    T("Scelta distanze in programma (Sprint, Olimpico, Medio, Lungo)", "Percorso", -300, "c", "Disattivare le attività delle distanze non previste."),
    T("Coordinamento con la federazione per giudici e delegato tecnico", "Autorizzazioni", -180, "c", V),
    T("Nulla osta specchio d'acqua (Capitaneria / ente gestore)", "Autorizzazioni", -150, "c", V),
    T("Ordinanza di chiusura strade per frazione ciclismo", "Autorizzazioni", -90, "c", V, "routes"),
    T("Studio percorso nuoto e batimetria", "Percorso", -180, "i", crm="routes"),
    T("Studio percorso ciclismo e giri", "Percorso", -180, "i", crm="routes"),
    T("Studio percorso corsa e giri", "Percorso", -180, "i", crm="routes"),
    T("Sopralluogo tecnico congiunto dei tre percorsi", "Percorso", -150, "i"),
    T("Misurazione e omologazione distanze", "Percorso", -60, "i", V),
    T("Sprint: percorso 750 m / 20 km / 5 km", "Percorso", -150, "n", "Solo se in programma."),
    T("Olimpico: percorso 1,5 km / 40 km / 10 km", "Percorso", -150, "n", "Solo se in programma."),
    T("Medio: percorso 1,9 km / 90 km / 21 km e ristori aggiuntivi", "Percorso", -180, "i", "Solo se in programma."),
    T("Lungo: percorso 3,8 km / 180 km / 42 km, special needs e illuminazione", "Percorso", -210, "i", "Solo se in programma."),
    T("Piano sicurezza in acqua (barche, canoe, SUP, sommozzatori)", "Sicurezza", -90, "c", f"Fornitore: salvamento. {V}"),
    T("Rapporto bagnini / atleti e posizionamento", "Sicurezza", -45, "c", V),
    T("Protocollo temperatura acqua e uso muta", "Sicurezza", -30, "c", V),
    T("Procedura di riduzione o annullamento frazione nuoto", "Sicurezza", -30, "c", "Criteri meteo, vento, onde, qualità dell'acqua."),
    T("Posizionamento boe e allineamenti", "Percorso", -1, "i"),
    T("Ordine boe di virata e di percorso", "Materiali", -60),
    T("Piano viabilità e presidi incroci frazione bici", "Sicurezza", -60, "c", crm="routes"),
    T("Scorte tecniche moto e veicoli di servizio", "Sicurezza", -60, "i", "Fornitore: scorte tecniche."),
    T("Gestione zone no-drafting e moto giudici", "Percorso", -30, "n", V),
    T("Presidi e segnaletica percorso corsa", "Sicurezza", -30, "i"),
    T("Progetto zona cambio T1/T2 (rastrelliere, corsie, flussi)", "Allestimenti", -90, "c"),
    T("Noleggio rastrelliere bici e moquette", "Allestimenti", -60, "i"),
    T("Procedura bike check-in / check-out e controllo caschi", "Logistica", -30, "i"),
    T("Sacche cambio e servizio deposito", "Logistica", -30, "n", "Necessarie per Medio e Lungo."),
    T("Tappeti cronometraggio per rilevamento frazioni", "Logistica", -30, "i", "Fornitore: cronometraggio."),
    T("Postazioni rilevamento intermedie e giri", "Logistica", -14, "n"),
    T("Ristori percorso bici (borracce, gel)", "Logistica", -30, "i"),
    T("Ristori percorso corsa e spugnaggi", "Logistica", -30, "i"),
    T("Area recupero atleti post arrivo", "Allestimenti", -14, "n"),
    T("Posto medico avanzato in zona arrivo", "Sicurezza", -30, "c", V),
    T("Assistenza meccanica in zona cambio", "Logistica", -30, "n", "Fornitore: assistenza meccanica."),
    T("Team volontari zona cambio", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Team volontari ristori", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Team volontari incroci e percorso bici", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Briefing tecnico atleti", "Comunicazione", -1, "i", "Regole zona cambio, drafting, penalità, cancelli.", "briefing"),
    T("Briefing sicurezza staff acqua", "Staff e volontari", -1, "c", crm="briefing"),
    T("Pubblicazione mappe percorsi e zona cambio", "Comunicazione", -30, "i", crm="routes"),
    T("Avviso a residenti e attività su chiusure strade", "Comunicazione", -14, "i"),
    T("Allestimento zona cambio", "Allestimenti", -1, "c"),
    T("Allestimento uscita acqua e corsia verso T1", "Allestimenti", -1, "i"),
    T("Controllo meteo e acqua la mattina della gara", "Sicurezza", 0, "c"),
    T("Gestione partenza a onde / rolling start", "Logistica", 0, "i"),
    T("Rimozione boe e ripristino specchio d'acqua", "Post evento", 0, "i"),
    T("Rimozione segnaletica e riapertura strade", "Post evento", 0, "i"),
]

NUOTO = [
    T("Definizione campo gara e distanze", "Percorso", -240, "c", crm="routes"),
    T("Analisi fondali, correnti e accessi al campo gara", "Percorso", -180, "i"),
    T("Verifica ordinanze balneari e autorizzazioni applicabili", "Autorizzazioni", -150, "c", V),
    T("Richiesta autorizzazione Capitaneria di Porto o ente gestore", "Autorizzazioni", -150, "c", V),
    T("Coordinamento con gestori di stabilimenti, porti o laghi", "Autorizzazioni", -120, "i"),
    T("Verifica qualità delle acque di balneazione", "Sicurezza", -30, "c", V),
    T("Progetto posizionamento boe e allineamenti GPS", "Percorso", -60, "i"),
    T("Ordine boe, corpi morti e cime", "Materiali", -60, "i"),
    T("Imbarcazioni di assistenza e soccorso", "Sicurezza", -60, "c", f"Fornitore: noleggio imbarcazioni / salvamento. {V}"),
    T("Personale di sicurezza in acqua (bagnini, canoe, SUP, sub)", "Sicurezza", -60, "c", V),
    T("Rapporto personale sicurezza / nuotatori", "Sicurezza", -45, "c", V),
    T("Mezzo di soccorso con medico a bordo", "Sicurezza", -45, "c", V),
    T("Protocollo temperatura acqua e obbligo muta", "Sicurezza", -30, "c", V),
    T("Procedure di sospensione o annullamento", "Sicurezza", -30, "c", "Criteri meteo, vento, onde, temperatura, visibilità."),
    T("Procedura conteggio entrata/uscita atleti", "Sicurezza", -30, "c", "Nessun atleta disperso: controllo numerico in uscita."),
    T("Servizio meteo marino dedicato", "Sicurezza", -14, "i"),
    T("Cuffie numerate e colori per batteria", "Materiali", -45, "i"),
    T("Marcatura numeri sugli atleti", "Logistica", -7),
    T("Struttura di partenza (spiaggia, pontone o in acqua)", "Allestimenti", -30, "i"),
    T("Arco e imbuto di arrivo con piastre", "Allestimenti", -30, "i", "Fornitore: cronometraggio."),
    T("Cronometraggio con chip alla caviglia", "Logistica", -30, "i", "Fornitore: cronometraggio."),
    T("Area riscaldamento e coperte termiche", "Logistica", -14, "n"),
    T("Posto medico all'arrivo", "Sicurezza", -30, "c", V),
    T("Team volontari spiaggia, partenza e arrivo", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Team volontari imbarcazioni", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Pubblicazione mappa campo gara", "Comunicazione", -30, "i", crm="routes"),
    T("Briefing sicurezza staff in acqua", "Staff e volontari", -1, "c", crm="briefing"),
    T("Briefing atleti con segnali di soccorso", "Comunicazione", 0, "c", "Come chiedere aiuto, uscite d'emergenza, cancelli.", "briefing"),
    T("Posizionamento boe il giorno prima", "Percorso", -1, "i"),
    T("Verifica condizioni meteo e acqua prima della partenza", "Sicurezza", 0, "c"),
    T("Recupero atleti ritirati e gestione emergenze", "Sicurezza", 0, "c"),
    T("Rimozione boe e ripristino dell'area", "Post evento", 0, "i"),
]

CICLISMO = [
    T("Definizione percorsi e distanze (gara, granfondo, mediofondo)", "Percorso", -270, "c", crm="routes"),
    T("Tracciatura GPX e altimetria", "Percorso", -210, "i", crm="routes"),
    T("Sopralluoghi tecnici del percorso", "Percorso", -180, "i"),
    T("Censimento punti critici (discese, incroci, rotatorie, passaggi a livello)", "Percorso", -150, "c"),
    T("Coordinamento con enti proprietari delle strade (ANAS, Province, Comuni)", "Autorizzazioni", -150, "c", V),
    T("Richiesta ordinanze di viabilità e chiusure", "Autorizzazioni", -90, "c", V, "routes"),
    T("Coordinamento con Polizia Stradale e Polizie Locali", "Autorizzazioni", -60, "c", V),
    T("Richiesta giudici di gara e direttore di corsa", "Autorizzazioni", -120, "i", V),
    T("Piano sicurezza e gestione intersezioni", "Sicurezza", -60, "c", V),
    T("Scorte tecniche moto", "Sicurezza", -60, "c", f"Fornitore: scorte tecniche. {V}"),
    T("Auto apripista, fine corsa e mezzo scopa", "Logistica", -45, "i"),
    T("Moto e auto di servizio per giuria e assistenza", "Logistica", -45, "n"),
    T("Segnaletica di percorso e frecce direzionali", "Materiali", -45, "i"),
    T("Cartellonistica di preavviso chiusura strade", "Materiali", -30, "i"),
    T("Transennamenti partenza, arrivo e curve pericolose", "Allestimenti", -30, "i"),
    T("Protezioni in materiale morbido nei punti critici", "Sicurezza", -21, "n"),
    T("Cronometraggio con chip e rilevamenti intermedi", "Logistica", -30, "i", "Fornitore: cronometraggio."),
    T("Ristori lungo il percorso", "Logistica", -30, "i"),
    T("Pasta party / ristoro finale", "Logistica", -21),
    T("Ambulanze lungo il percorso e medico in moto", "Sicurezza", -45, "c", V),
    T("Assistenza meccanica neutra (auto/moto)", "Logistica", -30, "i", "Fornitore: assistenza meccanica."),
    T("Area lavaggio bici e parcheggio custodito", "Logistica", -21),
    T("Team volontari incroci e presidi", "Staff e volontari", -45, "c", crm="volunteers"),
    T("Team volontari ristori", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Avviso ad abitanti e attività lungo il percorso", "Comunicazione", -21, "i", "Volantini, social, comunicati ai Comuni."),
    T("Comunicazione agli utenti della strada e media locali", "Comunicazione", -14, "i"),
    T("Pubblicazione tracce GPX e orari di chiusura", "Comunicazione", -30, "i", crm="routes"),
    T("Briefing direttore di corsa con scorte e presidi", "Staff e volontari", -1, "c", crm="briefing"),
    T("Allestimento griglie di partenza", "Allestimenti", -1, "i"),
    T("Controllo segnaletica il giorno prima", "Percorso", -1, "i"),
    T("Allestimento podio e area premiazioni", "Allestimenti", -1),
    T("Ripristino percorsi e rimozione segnaletica", "Post evento", 0, "i"),
]

MTB = [
    T("Progettazione tracciato XC / XCM / granfondo", "Percorso", -270, "c", crm="routes"),
    T("Tracciatura GPX e altimetria", "Percorso", -210, "i", crm="routes"),
    T("Sopralluoghi sentieri e individuazione punti tecnici", "Percorso", -180, "i"),
    T("Censimento proprietà e gestori dei terreni attraversati", "Autorizzazioni", -180, "c"),
    T("Permessi di transito e utilizzo delle aree", "Autorizzazioni", -150, "c", V),
    T("Rapporti con proprietari, consorzi e gestori del territorio", "Autorizzazioni", -150, "i"),
    T("Verifica vincoli ambientali, idrogeologici e aree protette", "Autorizzazioni", -150, "c", V),
    T("Nulla osta enti parco o forestali", "Autorizzazioni", -120, "c", V),
    T("Manutenzione e messa in sicurezza dei sentieri", "Percorso", -45, "i"),
    T("Linee alternative ai passaggi tecnici (chicken line)", "Percorso", -45, "n"),
    T("Segnaletica e tracciatura (frecce, fettucce, km)", "Materiali", -45, "i"),
    T("Tracciatura del percorso", "Percorso", -3, "c"),
    T("Presidi nei punti tecnici e discese", "Sicurezza", -30, "c"),
    T("Piano recupero atleti in aree difficili", "Sicurezza", -45, "c", V),
    T("Mezzi fuoristrada / quad per soccorso", "Sicurezza", -45, "c", f"Fornitore: soccorso / protezione civile. {V}"),
    T("Coordinamento con Soccorso Alpino, se previsto", "Sicurezza", -60, "i", V),
    T("Ambulanze ai punti di accesso e medico di gara", "Sicurezza", -45, "c", V),
    T("Copertura radio nelle zone senza segnale", "Sicurezza", -30, "i"),
    T("Assistenza meccanica e zone tecniche", "Logistica", -30, "i", "Fornitore: assistenza meccanica."),
    T("Ristori e punti acqua", "Logistica", -30, "i"),
    T("Trasporto materiali ai ristori in quota", "Logistica", -7, "n"),
    T("Cronometraggio e rilevamenti intermedi", "Logistica", -30, "i", "Fornitore: cronometraggio."),
    T("Area lavaggio bici", "Logistica", -21),
    T("Team volontari presidi percorso", "Staff e volontari", -45, "c", crm="volunteers"),
    T("Team volontari ristori", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Apripista e chiusura percorso (scopa)", "Staff e volontari", -14, "i"),
    T("Pubblicazione tracce GPX e mappa", "Comunicazione", -30, "i", crm="routes"),
    T("Briefing percorso e sicurezza atleti", "Comunicazione", 0, "i", crm="briefing"),
    T("Verifica meteo e praticabilità del tracciato", "Sicurezza", -1, "c"),
    T("Smontaggio segnaletica", "Post evento", 1, "i"),
    T("Ripristino ambientale dei sentieri", "Post evento", 3, "i", "Verifica con proprietari e enti."),
]

TRAIL = [
    T("Definizione distanze e dislivelli", "Percorso", -300, "c", crm="routes"),
    T("Studio del percorso e sopralluoghi", "Percorso", -240, "i"),
    T("Verifica proprietà e accessibilità dei sentieri", "Autorizzazioni", -210, "c"),
    T("Autorizzazioni di enti e amministrazioni competenti", "Autorizzazioni", -180, "c", V),
    T("Coordinamento con parchi e aree protette", "Autorizzazioni", -180, "c", V),
    T("Valutazione vincoli ambientali", "Autorizzazioni", -180, "i", V),
    T("Requisiti federali, ITRA e UTMB Index, se applicabili", "Iscrizioni", -210, "i", V),
    T("Materiale obbligatorio previsto dal regolamento", "Iscrizioni", -180, "i"),
    T("Tracciatura GPX definitiva", "Percorso", -120, "i", crm="routes"),
    T("Verifica punti critici e attraversamenti (strade, guadi, creste)", "Percorso", -90, "c"),
    T("Piano sicurezza e gestione emergenze", "Sicurezza", -60, "c", V),
    T("Coordinamento soccorso sanitario e Soccorso Alpino", "Sicurezza", -60, "c", V),
    T("Individuazione vie di evacuazione", "Sicurezza", -60, "c"),
    T("Comunicazioni radio nelle zone senza copertura telefonica", "Sicurezza", -30, "c"),
    T("Percorsi alternativi e procedure di sospensione", "Sicurezza", -45, "c", "Criteri meteo e soglie di attivazione."),
    T("Squadre apripista e chiusura percorso", "Staff e volontari", -30, "i"),
    T("Presidi nei punti critici", "Sicurezza", -30, "c"),
    T("Cancelli orari e tempi massimi", "Percorso", -90, "i"),
    T("Definizione posizione ristori", "Logistica", -90, "i"),
    T("Calcolo approvvigionamenti dei ristori", "Logistica", -30, "i"),
    T("Trasporto materiali nelle aree difficilmente accessibili", "Logistica", -3, "i", "Fornitore: trasporti / fuoristrada."),
    T("Gestione punti acqua", "Logistica", -30, "n"),
    T("Basi vita e punti cambio (ultra)", "Logistica", -45, "n", "Solo per distanze ultra."),
    T("Organizzazione deposito borse", "Logistica", -21),
    T("Gestione rifiuti e pulizia dei ristori", "Logistica", 0, "i", "Ristori plastic-free consigliati."),
    T("Calcolo volontari necessari per ristori e presidi", "Staff e volontari", -100, "i", crm="volunteers"),
    T("Team presidi percorso", "Staff e volontari", -45, "c", crm="volunteers"),
    T("Team ristori", "Staff e volontari", -45, "i", crm="volunteers"),
    T("Team partenza e arrivo", "Staff e volontari", -45, "n", crm="volunteers"),
    T("Briefing operativi e di sicurezza", "Staff e volontari", -2, "c", crm="briefing"),
    T("Coordinamento comunicazioni durante la gara", "Staff e volontari", 0, "c"),
    T("Comunicazione regolamento e materiale obbligatorio", "Comunicazione", -60, "i"),
    T("Pubblicazione tracce GPX", "Comunicazione", -45, "i", crm="routes"),
    T("Informazioni su ristori e cancelli orari", "Comunicazione", -30, "i"),
    T("Briefing pre-gara atleti", "Comunicazione", 0, "i", crm="briefing"),
    T("Allestimento partenza e arrivo", "Allestimenti", -1, "i"),
    T("Segnaletica e balisaggio del percorso", "Percorso", -2, "c"),
    T("Controllo segnaletica prima della partenza", "Percorso", 0, "i"),
    T("Verifica meteo prima della partenza", "Sicurezza", 0, "c"),
    T("Controllo materiale obbligatorio, se previsto", "Iscrizioni", 0, "i"),
    T("Gestione cancelli orari", "Logistica", 0, "i"),
    T("Monitoraggio passaggi atleti", "Logistica", 0, "i", "Fornitore: cronometraggio / live tracking."),
    T("Gestione ritiri e rientro atleti", "Sicurezza", 0, "c"),
    T("Coordinamento soccorsi in gara", "Sicurezza", 0, "c"),
    T("Smontaggio e rimozione segnaletica", "Post evento", 1, "i"),
    T("Verifica completa dei percorsi", "Post evento", 2, "i"),
    T("Ripristino ambientale", "Post evento", 3, "i"),
    T("Recupero materiali", "Post evento", 3),
]


def _build(fed, disc, specific):
    tasks = common(fed, disc) + specific
    return sorted(tasks, key=lambda t: t["giorni_offset"])


SPORT_TEMPLATES_SEED = [
    {"key": "triathlon", "name": "Triathlon", "order": 2, "tipologie": ["triathlon"],
     "description": "Pipeline per triathlon Sprint, Olimpico, Medio e Lungo: tre percorsi, zona cambio, sicurezza in acqua e su strada.",
     "tasks": _build("FITri", "triathlon", TRIATHLON)},
    {"key": "nuoto_acque_libere", "name": "Nuoto in acque libere", "order": 3, "tipologie": ["nuoto", "acque libere"],
     "description": "Pipeline per gare di nuoto in mare, lago o fiume: campo gara, boe, sicurezza in acqua e procedure meteo.",
     "tasks": _build("FIN", "nuoto in acque libere", NUOTO)},
    {"key": "ciclismo_strada", "name": "Ciclismo su strada", "order": 4, "tipologie": ["ciclismo", "granfondo", "bici"],
     "description": "Pipeline per gare e granfondo su strada: viabilità, ordinanze, scorte tecniche, segnaletica e assistenza.",
     "tasks": _build("FCI / ente di promozione", "ciclismo su strada", CICLISMO)},
    {"key": "mountain_bike", "name": "Mountain Bike", "order": 5, "tipologie": ["mountain bike", "mtb"],
     "description": "Pipeline per XC, XCM e granfondo MTB: permessi sui terreni, vincoli ambientali, tracciatura e soccorso in fuoristrada.",
     "tasks": _build("FCI / ente di promozione", "mountain bike", MTB)},
    {"key": "trail_running", "name": "Trail Running", "order": 6, "tipologie": ["trail"],
     "description": "Pipeline per Trail e Ultra Trail in ambiente naturale: sentieri, sicurezza, radio, ristori in quota e cancelli orari.",
     "tasks": _build("FIDAL / ente di promozione", "trail running", TRAIL)},
]


def suggest_template(tipologia: str) -> str | None:
    """Modello proposto in base alla Tipologia dell'evento (l'organizzatore può sceglierne un altro)."""
    t = (tipologia or "").strip().lower()
    if not t:
        return None
    for tpl in SPORT_TEMPLATES_SEED:  # ordine: triathlon prima di running; mtb prima di ciclismo
        if tpl["key"] == "ciclismo_strada":
            continue
        if any(k in t for k in tpl["tipologie"]):
            return tpl["key"]
    if any(k in t for k in ("ciclismo", "granfondo", "bici")):
        return "ciclismo_strada"
    if "running" in t or "corsa" in t or "maratona" in t:
        return "running"
    return None
